server:../apue.h ../error.c server.c
	gcc -o server -Wall -ggdb ../apue.h ../error.c server.c -lpthread
client:../apue.h ../error.c client.c
	gcc -o client -Wall -ggdb ../apue.h ../error.c client.c -lpthread
